### ISSUE TITLE
Parse error while loading profile

### ISSUE THREAD

**Issue by apsg** [wertarbyte/autorandr#28]
I have saved a preset and then tried to load it. The autorandr throws following error:

./autorandr --load 2m
 -> loading profile 2m
/usr/bin/xrandr: failed to parse 'x' as a position
Try '/usr/bin/xrandr --help' for more information.

How can I get it to work?

**Comment by phillipberndt** [comment]
This repository is currently unmaintained. Check if it is working with my fork at https://github.com/phillipberndt/autorandr. I've merged most of the pull requests others opened here, your problem was probably solved by one of them. If it wasn't, please open another issue there and post your stored configuration file from  the `~/.autorandr/` directory.

**Comment by apsg** [comment]
Yep, your fork works like a charm! Thanks

**Comment by sazawal** [comment]
@phillipberndt Smooth.
